objetodeaprendizaje/src/main/java/com/manriques/objetodeaprendizaje/mb/EncuestaController.java
package com.manriques.objetodeaprendizaje.mb;

import com.manriques.objetodeaprendizaje.modelo.*;
import com.manriques.objetodeaprendizaje.mb.util.JsfUtil;
import com.manriques.objetodeaprendizaje.mb.util.PaginationHelper;
import com.manriques.objetodeaprendizaje.modeloDTO.AutorDTO;
import com.manriques.objetodeaprendizaje.modeloDTO.ObjetoAprendizajeDTO;
import com.manriques.objetodeaprendizaje.persistencia.EncuestaFacade;

import java.io.IOException;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.faces.context.ExternalContext;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.ArrayDataModel;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

import com.manriques.objetodeaprendizaje.persistencia.ObjetoAprendizajeFacade;
import org.primefaces.PrimeFaces;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.event.UnselectEvent;
import org.primefaces.model.DualListModel;

@Named("encuestaController")
@SessionScoped
public class EncuestaController implements Serializable {

    private Encuesta current;
    private DataModel items = null;
    @EJB
    private com.manriques.objetodeaprendizaje.persistencia.EncuestaFacade ejbFacade;
    @EJB
    private com.manriques.objetodeaprendizaje.persistencia.DimensionFacade ejbFacadeDimension;
    @EJB
    private ObjetoAprendizajeFacade ejbObjetoAprendizaje;

    private PaginationHelper pagination;
    private int selectedItemIndex;
    private String capa = "";
    private DualListModel<Dimension> dimension = new DualListModel<>();
    private ObjetoAprendizajeDTO objetoSeleccionado;
    private List<Encuesta> pendientes = new ArrayList<>();
    private List<Encuesta> enviadas = new ArrayList<>();
    private List<Encuesta> misEncuestas = new ArrayList<>();

    public List<Encuesta> getMisEncuestas() {
        return misEncuestas;
    }

    public void setMisEncuestas(List<Encuesta> misEncuestas) {
        this.misEncuestas = misEncuestas;
    }

    public List<Encuesta> getPendientes() {
        return pendientes;
    }

    public void setPendientes(List<Encuesta> pendientes) {
        this.pendientes = pendientes;
    }

    public List<Encuesta> getEnviadas() {
        return enviadas;
    }

    public void setEnviadas(List<Encuesta> enviadas) {
        this.enviadas = enviadas;
    }

    public DualListModel<Dimension> getDimension() {
        return dimension;
    }

    public void setDimension(DualListModel<Dimension> dimension) {
        this.dimension = dimension;
    }

    public ObjetoAprendizajeDTO getObjetoSeleccionado() {
        return objetoSeleccionado;
    }

    public void setObjetoSeleccionado(ObjetoAprendizajeDTO objetoSeleccionado) {
        this.objetoSeleccionado = objetoSeleccionado;
    }

    public void seleccionCapa() {
        try {
            List<Dimension> dimensiones;
            if (capa.equals("Usuario")) {
                dimensiones = this.ejbFacadeDimension.buscardimensionesporcapa(2);
                dimension = new DualListModel<Dimension>(dimensiones, new ArrayList<Dimension>());
            }
            if (capa.equals("Experto")) {
                dimensiones = this.ejbFacadeDimension.buscardimensionesporcapa(1);
                dimension = new DualListModel<Dimension>(dimensiones, new ArrayList<Dimension>());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    public String getCapa() {
        return capa;
    }

    public void setCapa(String capa) {
        this.capa = capa;
    }


    public EncuestaController() {
    }

    public Encuesta getSelected() {
        if (current == null) {
            current = new Encuesta();
            selectedItemIndex = -1;
        }
        return current;
    }

    public void setCurrent(Encuesta current) {
        this.current = current;
    }


    private EncuestaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public void prepareList() {
        recreateModel();
        FacesContext contexto = FacesContext.getCurrentInstance();
        UsuarioController usuarioController = (UsuarioController) contexto.getApplication().evaluateExpressionGet(contexto, "#{usuarioController}", UsuarioController.class);
        if (usuarioController.getLogueado().getRol().getDescripcion().equals("Administrador")) {
            this.misEncuestas = ejbFacade.findAll();
        } else {
            this.misEncuestas = ejbFacade.encuestasPorUsuario(usuarioController.getLogueado().getId());
        }

        this.redireccion("/faces/encuesta/List.xhtml");
    }

    public String prepareView() {
        current = (Encuesta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Encuesta();
        selectedItemIndex = -1;
        dimension = new DualListModel<Dimension>(new ArrayList<Dimension>(), new ArrayList<Dimension>());

        return "Create";
    }

    public String create() {
        FacesContext contexto = FacesContext.getCurrentInstance();
        ExpertoController expertoController = (ExpertoController) contexto.getApplication().evaluateExpressionGet(contexto, "#{expertoController}", ExpertoController.class);
        UsuarioController usuarioController = (UsuarioController) contexto.getApplication().evaluateExpressionGet(contexto, "#{usuarioController}", UsuarioController.class);
        EncuestaController encuestaController = (EncuestaController) contexto.getApplication().evaluateExpressionGet(contexto, "#{encuestaController}", EncuestaController.class);
        AlumnoController alumnoController = (AlumnoController) contexto.getApplication().evaluateExpressionGet(contexto, "#{alumnoController}", AlumnoController.class);
        //List<Encuestado> listaEncuestados = expertoController.getExpertosSeleccionados();

        try {
            ObjetoAprendizaje objetoAprendizaje = this.ejbObjetoAprendizaje.bucarObjetoPorIdentificador(objetoSeleccionado.getId());
            if (objetoAprendizaje == null) objetoAprendizaje = nuevoObjetoAprendizaje();
            List<Encuestado> seleccionados = new ArrayList<>();
            if (encuestaController.getCapa().equalsIgnoreCase("experto")) {
                seleccionados = expertoController.obtenerEncuestadosSeleccionados();
            } else {
                seleccionados = alumnoController.obtenerAlumnosSeleccionados();
            }

            String[] encuestados = new String[seleccionados.size()];
            /*for (Dimension d : dimension.getTarget()) {
                System.out.println("d: " + d.getId() + d.getNombre());
            }*/

            /*---------------------------------------------------DESHARCODEAR ID USUARIO CREADOR ENCUESTA ------------------------------------------------*/
            current.setObjetoaprendizaje(objetoAprendizaje);
            current.setEncuestador(usuarioController.getLogueado());
            current.setDimensiones(dimension.getTarget());
            current.setEncuestados(seleccionados);
            current.setFechacreacion(new Date());

            getFacade().edit(current);
            for (int i = 0; i < seleccionados.size(); i++) {
                encuestados[i] = seleccionados.get(i).getMail();
            }

            JsfUtil.addSuccessMessage("Encuesta creada correctamente");

            EmailController.enviarInvitacionPorEmail(encuestados, usuarioController.getLogueado().getEncuestado().getApellido() + ", " + usuarioController.getLogueado().getEncuestado().getNombre());

            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, "Error al crear encuesta");
            return null;
        }
    }

    private ObjetoAprendizaje nuevoObjetoAprendizaje() {
        FacesContext contexto = FacesContext.getCurrentInstance();
        ObjetoAprendizajeController objetoAprendizajeController = (ObjetoAprendizajeController) contexto.getApplication().evaluateExpressionGet(contexto, "#{objetoAprendizajeController}", ObjetoAprendizajeController.class);
        List<String> autores = new ArrayList<>();
        for (AutorDTO autor : objetoSeleccionado.getAuthor()) {
            autores.add(autor.getName());
        }
        ObjetoAprendizaje objetoAprendizaje = new ObjetoAprendizaje();
        objetoAprendizaje.setAutores(autores);
        objetoAprendizaje.setDescripcion(objetoSeleccionado.getDescription());
        objetoAprendizaje.setFechacreacion(objetoSeleccionado.getPublished());
        objetoAprendizaje.setIdentificador(objetoSeleccionado.getId());
        objetoAprendizaje.setRepositorio(objetoAprendizajeController.getRepositorioSeleccinado());
        objetoAprendizaje.setTitulo(objetoSeleccionado.getTitle());
        return objetoAprendizaje;
    }

    public String prepareEdit() {
        current = (Encuesta) getItems().getRowData();

objetodeaprendizaje/src/main/webapp/encuestado/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateEncuestadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <div class="Container50 Responsive100 centerCard" style="margin: auto; float:none;">
                <div class="Card">
                <div class="CardTopic"><i class="pi pi-clone Fs30 Fleft MarRight10"></i>
                    <h3>Nueva Encuestado</h3>
                </div>
                <div class="SeparatorFull"></div>
                <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true"
                            severity="info,fatal,warn"/>
                <h:panelGrid columns="2" width="100%" id="pnlCrear" style="font-size: 12px" styleClass="tableInput">
                    <p:outputLabel value="#{bundle.CreateEncuestadoLabel_apellido}" for="apellido" />
                    <p:inputText id="apellido" value="#{encuestadoController.selected.apellido}" title="#{bundle.CreateEncuestadoTitle_apellido}" />
                   
                    <p:outputLabel value="#{bundle.CreateEncuestadoLabel_mail}" for="mail" />
                    <p:inputText id="mail" value="#{encuestadoController.selected.mail}" title="#{bundle.CreateEncuestadoTitle_mail}" />
                    <p:outputLabel value="#{bundle.CreateEncuestadoLabel_edad}" for="edad" />
                    <p:inputText id="edad" value="#{encuestadoController.selected.edad}" title="#{bundle.CreateEncuestadoTitle_edad}" />
                    <p:outputLabel value="#{bundle.CreateEncuestadoLabel_nombre}" for="nombre" />
                    <p:inputText id="nombre" value="#{encuestadoController.selected.nombre}" title="#{bundle.CreateEncuestadoTitle_nombre}" />
        
                </h:panelGrid>
                    <br/>
                    <center>
                        <p:commandButton action="#{encuestadoController.create}" value="Guardar" styleClass="botonfondo botonTamanio"/>
                    </center>


                </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/encuestado/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template.xhtml">
    <ui:define name="title">
        <h:outputText value="#{bundle.EditEncuestadoTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
        <h:panelGroup id="messagePanel" layout="block">
            <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
        </h:panelGroup>
        <h:form>
            <div class="Container50 Responsive100 centerCard" style="margin: auto; float:none;">
                <div class="Card">
                    <div class="CardTopic"><i class="pi pi-clone Fs30 Fleft MarRight10"></i>
                        <h3>Editar Usuario</h3>
                    </div>
                    <div class="SeparatorFull"></div>
                    <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true"
                                severity="info,fatal,warn"/>
                    <h:panelGrid columns="2" width="100%" id="pnlCrear" style="font-size: 12px" styleClass="tableInput">

                        <p:outputLabel value="Tipo de Usuario" for="tipoUsuario"/>
                        <p:selectOneMenu id="tipoUsuario" value="#{encuestadoController.currentEdit.tipo}"
                                         required="true"
                                         title="Tipo de usuario" style="width: 29%;">
                            <f:selectItem itemLabel="Alumno" itemValue="Alumno"/>
                            <f:selectItem itemLabel="Experto" itemValue="Experto"/>
                            <p:ajax event="change" update="pnlCrear"
                                    listener="#{encuestadoController.habilitarCampos()}"/>
                        </p:selectOneMenu>

                        <p:outputLabel value="Nombre" for="nombre"/>
                        <p:inputText id="nombre" value="#{encuestadoController.currentEdit.nombre}"
                                     title="nombre"/>

                        <p:outputLabel value="Apellido" for="apellido"/>
                        <p:inputText id="apellido" value="#{encuestadoController.currentEdit.apellido}"
                                     title="Apellido"/>

                        <p:outputLabel value="Email" for="email"/>
                        <p:inputText id="email" value="#{encuestadoController.currentEdit.mail}"
                                     title="email"/>

                        <p:outputLabel value="Edad" for="edad"/>
                        <p:inputText id="edad" value="#{encuestadoController.currentEdit.edad}"
                                     title="edad"/>

                        <p:outputLabel value="Especialidad" for="especialidad"/>
                        <p:inputText id="especialidad" value="#{encuestadoController.currentEdit.especialidad}"
                                     title="especialidad"
                                     disabled="#{!encuestadoController.esExperto}"/>

                        <p:outputLabel value="Curso" for="curso"/>
                        <p:inputText id="curso" value="#{encuestadoController.currentEdit.curso}"
                                     title="curso" disabled="#{encuestadoController.esExperto}"/>

                        <p:outputLabel value="Carrera" for="carrera"/>
                        <p:inputText id="carrera" value="#{encuestadoController.currentEdit.carrera}"
                                     title="carrera" disabled="#{encuestadoController.esExperto}"/>

                    </h:panelGrid>
                    <br/>
                    <center>
                        <p:commandButton action="#{encuestadoController.create}" value="Guardar cambios"
                                         styleClass="botonfondo botonTamanio"/>
                    </center>


                </div>
            </div>
        </h:form>
    </ui:define>
</ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/encuestado/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

<ui:composition template="/template.xhtml">
    <ui:define name="title">
        <h:outputText value="#{bundle.ListEncuestadoTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
        <h:form styleClass="jsfcrud_list_form">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:panelGroup rendered="#{encuestadoController.objects.size() > 0}">
                <p:dataTable value="#{encuestadoController.objects}" emptyMessage="No se encontraron registros"
                             id="encuestados"
                             paginator="true" rows="10"
                             paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                             currentPageReportTemplate="({startRecord} - {endRecord}) de {totalRecords} Usuarios"
                             style="font-size: 12px" var="item"
                             reflow="true">

                    <p:column headerText="Nombre">
                        <p:outputLabel value="#{item.nombre}"/>
                    </p:column>
                    <p:column headerText="Apellido">

                        <p:outputLabel value="#{item.apellido}"/>
                    </p:column>
                    <p:column headerText="Edad">

                        <p:outputLabel value="#{item.edad}"/>
                    </p:column>
                    <p:column headerText="Email">
                        <p:outputLabel value="#{item.mail}"/>
                    </p:column>
                    <p:column headerText="Tipo">
                        <p:outputLabel value="#{item.tipo}"/>
                    </p:column>
                    <p:column headerText="Rol">
                        <p:outputLabel value="#{item.usuario.rol.descripcion}"/>
                    </p:column>
                    <p:column headerText="Carrera">
                        <p:outputLabel value="#{item.carrera}"/>
                    </p:column>
                    <p:column headerText="Curso">
                        <p:outputLabel value="#{item.curso}"/>
                    </p:column>
                    <p:column headerText="Especialidad">
                        <p:outputLabel value="#{item.especialidad}"/>
                    </p:column>

                    <p:column>
                        <p:commandButton action="#{encuestadoController.prepareEdit}" icon="pi pi-pencil"
                                         value="Editar"
                                         styleClass="botonfondo">
                            <f:setPropertyActionListener value="#{item}" target="#{encuestadoController.currentEdit}"/>
                        </p:commandButton>
                    </p:column>

                </p:dataTable>
            </h:panelGroup>

        </h:form>
    </ui:define>
</ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/encuestado/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewEncuestadoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_apellido}"/>
                    <h:outputText value="#{encuestadoController.selected.apellido}" title="#{bundle.ViewEncuestadoTitle_apellido}"/>
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_tipo}"/>
                    <h:outputText value="#{encuestadoController.selected.tipo}" title="#{bundle.ViewEncuestadoTitle_tipo}"/>
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_mail}"/>
                    <h:outputText value="#{encuestadoController.selected.mail}" title="#{bundle.ViewEncuestadoTitle_mail}"/>
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_edad}"/>
                    <h:outputText value="#{encuestadoController.selected.edad}" title="#{bundle.ViewEncuestadoTitle_edad}"/>
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_nombre}"/>
                    <h:outputText value="#{encuestadoController.selected.nombre}" title="#{bundle.ViewEncuestadoTitle_nombre}"/>
                    <h:outputText value="#{bundle.ViewEncuestadoLabel_id}"/>
                    <h:outputText value="#{encuestadoController.selected.id}" title="#{bundle.ViewEncuestadoTitle_id}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{encuestadoController.destroyAndView}" value="#{bundle.ViewEncuestadoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewEncuestadoEditLink}"/>
                <br />
                <h:commandLink action="#{encuestadoController.prepareCreate}" value="#{bundle.ViewEncuestadoCreateLink}" />
                <br />
                <h:commandLink action="#{encuestadoController.prepareList}" value="#{bundle.ViewEncuestadoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewEncuestadoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>