objetodeaprendizaje/src/main/java/com/manriques/objetodeaprendizaje/mb/RespuestaController.java
package com.manriques.objetodeaprendizaje.mb;

import com.manriques.objetodeaprendizaje.modelo.Respuesta;
import com.manriques.objetodeaprendizaje.mb.util.JsfUtil;
import com.manriques.objetodeaprendizaje.mb.util.PaginationHelper;
import com.manriques.objetodeaprendizaje.modelo.Formula;
import com.manriques.objetodeaprendizaje.persistencia.RespuestaFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.ArrayDataModel;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("respuestaController")
@SessionScoped
public class RespuestaController implements Serializable {

    private Respuesta current;
    private DataModel items = null;
    @EJB
    private com.manriques.objetodeaprendizaje.persistencia.RespuestaFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public RespuestaController() {
    }

    public Respuesta getSelected() {
        if (current == null) {
            current = new Respuesta();
            selectedItemIndex = -1;
        }
        return current;
    }

    private RespuestaFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

     public String prepareList() {
        recreateModel();
        items = new ArrayDataModel<Respuesta>((Respuesta[]) getFacade().findAll().toArray());
        return "List";
    }

    public String prepareView() {
        current = (Respuesta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Respuesta();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RespuestaCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Respuesta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RespuestaUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Respuesta) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("RespuestaDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Respuesta getRespuesta(int id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Respuesta.class)
    public static class RespuestaControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RespuestaController controller = (RespuestaController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "respuestaController");
            return controller.getRespuesta(getKey(value));
        }

        int getKey(String value) {
            int key;
            key = Integer.parseInt(value);
            return key;
        }

        String getStringKey(int value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Respuesta) {
                Respuesta o = (Respuesta) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Respuesta.class.getName());
            }
        }

    }

}

objetodeaprendizaje/src/main/webapp/respuesta/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateRespuestaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <div class="Container50 Responsive100 centerCard" style="margin: auto; float:none;">
                <div class="Card">
                <div class="CardTopic"><i class="pi pi-clone Fs30 Fleft MarRight10"></i>
                    <h3>Crear respuesta</h3>
                </div>
                <div class="SeparatorFull"></div>
                <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true"
                            severity="info,fatal,warn"/>
                <h:panelGrid columns="2" width="100%" id="pnlCrear" style="font-size: 12px" styleClass="tableInput">


                    <p:outputLabel value="#{bundle.CreateRespuestaLabel_resultado}" for="resultado" />
                    <p:selectOneMenu id="resultado" value="#{respuestaController.selected.resultado}" title="#{bundle.CreateRespuestaTitle_resultado}" >
                        <f:selectItems value="#{resultadoEncuestaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <p:outputLabel value="#{bundle.CreateRespuestaLabel_valorrespuesta}" for="valorrespuesta" />
                    <p:inputText id="valorrespuesta" value="#{respuestaController.selected.valorrespuesta}" title="#{bundle.CreateRespuestaTitle_valorrespuesta}" />
                </h:panelGrid>
                    <br/>
                    <center>
                        <p:commandButton action="#{respuestaController.create}" value="Guardar" styleClass="botonfondo botonTamanio"/>
                    </center>


                </div>
                </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/respuesta/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditRespuestaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <div class="Container50 Responsive100 centerCard" style="margin: auto; float:none;">
                    <div class="Card">
                        <div class="CardTopic"><i class="pi pi-clone Fs30 Fleft MarRight10"></i>
                            <h3>Editar respuesta</h3>
                        </div>
                        <div class="SeparatorFull"></div>
                        <p:messages id="messages" showDetail="true" autoUpdate="true" closable="true"
                                    severity="info,fatal,warn"/>
                <h:panelGrid columns="2" width="100%" id="pnlCrear" style="font-size: 12px" styleClass="tableInput">
                    <p:outputLabel value="#{bundle.CreateRespuestaLabel_resultado}" for="resultado" />
                    <p:selectOneMenu id="resultado" value="#{respuestaController.selected.resultado}" title="#{bundle.CreateRespuestaTitle_resultado}" >
                        <f:selectItems value="#{resultadoEncuestaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <p:outputLabel value="#{bundle.CreateRespuestaLabel_valorrespuesta}" for="valorrespuesta" />
                    <p:inputText id="valorrespuesta" value="#{respuestaController.selected.valorrespuesta}" title="#{bundle.CreateRespuestaTitle_valorrespuesta}" />
                </h:panelGrid>
                <br/>
                <center>
                    <p:commandButton action="#{respuestaController.create}" value="Guardar cambios" styleClass="botonfondo botonTamanio"/>
                </center>


            </div>
        </div>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/respuesta/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListRespuestaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListRespuestaEmpty}" rendered="#{respuestaController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{respuestaController.items.rowCount > 0}">
                    <h:outputText value="#{respuestaController.pagination.pageFirstItem + 1}..#{respuestaController.pagination.pageLastItem + 1}/#{respuestaController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{respuestaController.previous}" value="#{bundle.Previous} #{respuestaController.pagination.pageSize}" rendered="#{respuestaController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{respuestaController.next}" value="#{bundle.Next} #{respuestaController.pagination.pageSize}" rendered="#{respuestaController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{respuestaController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRespuestaTitle_id}"/>
                            </f:facet>
                            <h:outputText value="#{item.id}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRespuestaTitle_idpregunta}"/>
                            </f:facet>
                            <h:outputText value="#{item.idpregunta}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRespuestaTitle_resultado}"/>
                            </f:facet>
                            <h:outputText value="#{item.resultado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRespuestaTitle_valorrespuesta}"/>
                            </f:facet>
                            <h:outputText value="#{item.valorrespuesta}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{respuestaController.prepareView}" value="#{bundle.ListRespuestaViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{respuestaController.prepareEdit}" value="#{bundle.ListRespuestaEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{respuestaController.destroy}" value="#{bundle.ListRespuestaDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{respuestaController.prepareCreate}" value="#{bundle.ListRespuestaCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListRespuestaIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

objetodeaprendizaje/src/main/webapp/respuesta/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewRespuestaTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewRespuestaLabel_id}"/>
                    <h:outputText value="#{respuestaController.selected.id}" title="#{bundle.ViewRespuestaTitle_id}"/>
                    <h:outputText value="#{bundle.ViewRespuestaLabel_idpregunta}"/>
                    <h:outputText value="#{respuestaController.selected.idpregunta}" title="#{bundle.ViewRespuestaTitle_idpregunta}"/>
                    <h:outputText value="#{bundle.ViewRespuestaLabel_resultado}"/>
                    <h:outputText value="#{respuestaController.selected.resultado}" title="#{bundle.ViewRespuestaTitle_resultado}"/>
                    <h:outputText value="#{bundle.ViewRespuestaLabel_valorrespuesta}"/>
                    <h:outputText value="#{respuestaController.selected.valorrespuesta}" title="#{bundle.ViewRespuestaTitle_valorrespuesta}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{respuestaController.destroyAndView}" value="#{bundle.ViewRespuestaDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewRespuestaEditLink}"/>
                <br />
                <h:commandLink action="#{respuestaController.prepareCreate}" value="#{bundle.ViewRespuestaCreateLink}" />
                <br />
                <h:commandLink action="#{respuestaController.prepareList}" value="#{bundle.ViewRespuestaShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewRespuestaIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>